neko_pref_datasets:
- name: neko-llm/dna_dpo_hh-rlhf # OK
  config: default
  split: train
  instruction_field: question
  chosen_field: preferred_output
  rejected_field: non_preferred_output
  from_id: 0
  to_id: 49026
- name: neko-llm/DNA_DPO_hh-rlhf-classified # OK
  config: default
  split: train
  instruction_field: question
  chosen_field: preferred_output
  rejected_field: non_preferred_output
  from_id: 0
  to_id: 99
- name: neko-llm/DNA_DPO_Adversarial_vanilla
  config: train
  #split: train
  instruction_field: question
  chosen_field: preffered_output # <- ここで解決
  rejected_field: non_preffered_output # <- ここで解決s
  from_id: 0
  to_id: 1124
- name: neko-llm/HLE_DPO_HarmfulQA # OK
  config: default
  split: train
  instruction_field: question 
  chosen_field: preferred_output 
  rejected_field: non_preferred_output
  from_id: 0
  to_id: 247
- name: neko-llm/DPO_Adversarial_vanilla_ver2
  config: train
  #split: train
  instruction_field: question 
  chosen_field: preferred_output 
  rejected_field: non_preferred_output
  from_id: 0
  to_id: 1799