services:
  app:
    image: llm2025compet
    runtime: ${DOCKER_RUNTIME:-nvidia}
    command: ["tail", "-f", "/dev/null"]
    environment:
      # Configure Nvidia Docker interface (only used when DOCKER_RUNTIME=nvidia)
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-all}
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES:-all}
      - NVIDIA_REQUIRE_CUDA=${NVIDIA_REQUIRE_CUDA:-cuda>=12.8}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./:/app
    network_mode: host
