evaluation_settings:
  dataset_path: ../../datasets/Instruction/do_not_answer_en.csv
  log_wandb: true
  max_questions: null
  output_dir: ./evaluation_results/team1_llama2-7b-chat-finetune
  wandb_project: llm-competition-do-not-answer
model:
  description: Team 1 fine-tuned LLaMA2-7B-Chat model
  name: team1/llama2-7b-chat-finetune
  system_prompt: null
