# GRPO Training Configuration

# Environment settings
gpus_per_node: 8
nnodes: 2
wandb_entity: "LLMcompe-Team-Watanabe"
wandb_project_name: "competition_verl_grpo"
wandb_run_name: "llama3.2_GRPO_multinode"

# Algorithm configuration
algorithm:
  adv_estimator: grpo
  use_kl_in_reward: false

# Data configuration
data:
  train_files: "/home/Competition2025/P04/shareP04/data/gsm8k/train.parquet"
  val_files: "/home/Competition2025/P04/shareP04/data/gsm8k/test.parquet"
  train_batch_size: 256
  max_prompt_length: 512
  max_response_length: 512
  filter_overlong_prompts: true
  truncation: error

# Model configuration - Actor/Rollout/Reference
actor_rollout_ref:
  model:
    path: "/home/Competition2025/P04/shareP04/models/Llama-3.2-1B-Instruct"
    use_remove_padding: true
    enable_gradient_checkpointing: true
  
  actor:
    optim:
      lr: 1.0e-6
    ppo_mini_batch_size: 128
    ppo_micro_batch_size_per_gpu: 8
    use_kl_loss: true
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    entropy_coeff: 0
    fsdp_config:
      param_offload: false
      optimizer_offload: false
  
  rollout:
    log_prob_micro_batch_size_per_gpu: 8
    tensor_model_parallel_size: 1
    name: vllm
    gpu_memory_utilization: 0.85
    max_num_batched_tokens: 1024
    n: 5  # Generate 5 responses per prompt for GRPO
  
  ref:
    log_prob_micro_batch_size_per_gpu: 8
    fsdp_config:
      param_offload: true

# Trainer configuration
trainer:
  critic_warmup: 0
  logger:
    - console
    - wandb
  save_freq: 10
  test_freq: 5
  total_epochs: 15
  default_local_dir_suffix: "/training/multinode/grpo/checkpoints/llama3.2"