# sub dataset
# NOTE: required llm-2025-sahara organization's HF_TOKEN
# it's not your personal HF_TOKEN
# use full dataset if cannot access to it
dataset: llm-2025-sahara/hle-10fold
# now hle-10fold have test split which is the same as validation
split: test

# Category filter: Biology/Medicine, Chemistry, Computer Science/AI, Engineering, 
# Humanities/Social Science, Math, Other, Physics. If empty, use full dataset
category:

# full dataset
# dataset: cais/hle

provider: vllm # [vllm]

base_url: http://localhost:8000/v1

model: Qwen/Qwen3-235B-A22B
max_completion_tokens: 65536
reasoning: true

# sample with multimodal is 2500, so text-only sample is about 2400
num_workers: 2500
max_samples: 2500

judge: deepseek-ai/DeepSeek-R1-Distill-Llama-70B

# for saving artifacts to wandb
use_wandb: true
